#docker build -t stori-card-challenge-lambda .
FROM golang:1.20.6-alpine3.18 as compiler

WORKDIR /go/src/github.com/matiaspascansky/stori-card-challenge
COPY . .


#
# Run stage
#

FROM alpine

COPY --from=compiler /go/src /go/src
RUN apk add --no-cache tzdata
WORKDIR /go/src/github.com/matiaspascansky/stori-card-challenge
EXPOSE 8080