// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	transaction "stori-card-challenge/domain/transaction"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// GetTransactionsFromS3 provides a mock function with given fields: bucket, key
func (_m *TransactionRepository) GetTransactionsFromS3(bucket string, key string) ([]transaction.Transaction, error) {
	ret := _m.Called(bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsFromS3")
	}

	var r0 []transaction.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]transaction.Transaction, error)); ok {
		return rf(bucket, key)
	}
	if rf, ok := ret.Get(0).(func(string, string) []transaction.Transaction); ok {
		r0 = rf(bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transaction.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
